[features]
seeds = false
skip-lint = false
[programs.localnet]
eclipse = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.injective.eclipsenetwork.xyz:8899/"
wallet = "/Users/pratham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
